import './globals.css'
import { Inter } from 'next/font/google'
import {Button, ConfigProvider} from "antd";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <ConfigProvider
          theme={{
            token: {
              colorPrimary: '#00b96b',
            },
          }}
      >
        <Button>Chan vc;</Button>
        {children}
      </ConfigProvider>
      </body>
    </html>
  )
}
