import './globals.css'
import {Inter} from 'next/font/google'
import {Button, ConfigProvider} from "antd";
import InnerLayout from "@/app/inner-layout";
import {getServerSession} from "next-auth";
import {GetServerSidePropsContext} from "next";
import {SessionProvider} from "next-auth/react";
import {authOptions} from "@/app/api/auth/[...nextauth]/route";

const inter = Inter({subsets: ['latin']})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({children, params}: any) {
    const session = await getServerSession(authOptions);
    return (
        <html lang="en">
        <body className={inter.className}>
            <InnerLayout params={params} session={session}>{children}</InnerLayout>
        </body>
        </html>
    )
}
